version: '3'
services:
  todos.repository.mongodb:
    image: earthw0rm/todos.repository.mongodb:${TAG}
    build:
      context: ./mongo/
      dockerfile: Dockerfile
    expose:
      - "27017"
    networks:
      db-network:
        aliases:
        - todos_repository_mongodb


  todos.nodeapi:
    image: earthw0rm/todos.nodeapi:${TAG}
    build:
      context: ./backend-app/
      dockerfile: Dockerfile
    expose:
      - "${BACKEND_API_PORT}"
    ports:
      - "${EXPOSE_API_PORT}:${BACKEND_API_PORT}"
    depends_on:
      - todos.repository.mongodb
    networks:
      - db-network
    environment:
      - API_PORT=${BACKEND_API_PORT}
      - CONNECTIONSTRING=mongodb://reactBack:senha123@todos_repository_mongodb:27017
networks:
  db-network:
    driver: bridge