version: '3'
services:
  todos_repository_mongodb:
    image: earthw0rm/todos_mongodb:dev
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1GB
      restart_policy:
        condition: on-failure
    build:
      context: ./mongo/
      dockerfile: Dockerfile
    expose:
      - "27017"
    networks:
      webnet:
        aliases:
        - todos_repository_mongodb

  todos_nodeapi:
    image: earthw0rm/todos_nodeapi:dev
    build:
      context: ./backend-app/
      dockerfile: Dockerfile
    expose:
      - "3003"
    ports:
      - "8080:3003"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 512MB
      restart_policy:
        condition: on-failure      
    depends_on:
      - todos_repository_mongodb
    networks:
      - webnet
networks:
  webnet: